/**
 * send-dropin-notifications
 * ─────────────────────────
 * Supabase Edge Function — runs daily via Deno Cron at 13:00 UTC (8:00am EST / 9:00am EDT).
 *
 * For every user who has a drop-in alert matching a session happening today,
 * this function sends a Web Push notification to all of their registered
 * browser subscriptions.
 *
 * Required Supabase secrets (set via `supabase secrets set`):
 *   VAPID_PUBLIC_KEY   — base64url ECDH public key generated by web-push
 *   VAPID_PRIVATE_KEY  — base64url ECDH private key
 *   VAPID_SUBJECT      — mailto: or https: contact URI (e.g. mailto:admin@example.com)
 *   SUPABASE_URL       — auto-injected by Supabase runtime
 *   SUPABASE_SERVICE_ROLE_KEY — auto-injected; gives admin DB access (bypasses RLS)
 */

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// ── Deno Cron — runs daily at 08:00 EST (13:00 UTC) ──────────────────────────
Deno.cron("send-dropin-notifications", "0 13 * * *", async () => {
  await runNotifications();
});

// Also handle direct HTTP invocations (for manual testing / CI)
Deno.serve(async (_req) => {
  await runNotifications();
  return new Response(JSON.stringify({ ok: true }), {
    headers: { "Content-Type": "application/json" },
  });
});

// ── Main logic ────────────────────────────────────────────────────────────────

async function runNotifications() {
  const supabaseUrl     = Deno.env.get("SUPABASE_URL")!;
  const serviceRoleKey  = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const vapidPublicKey  = Deno.env.get("VAPID_PUBLIC_KEY")!;
  const vapidPrivateKey = Deno.env.get("VAPID_PRIVATE_KEY")!;
  const vapidSubject    = Deno.env.get("VAPID_SUBJECT")!;

  const supabase = createClient(supabaseUrl, serviceRoleKey);

  // Today's date in YYYY-MM-DD (UTC — matches stored first_date values)
  const todayStr = new Date().toISOString().slice(0, 10);

  // ── 1. Find all alerts that have at least one matching session today ─────────
  //    Join: user_dropin_alerts → dropins (by location_id + course_title ILIKE)
  //    Filter: first_date = today; optional time window from saved alert times.
  //
  //    We can't do a JOIN with ILIKE in PostgREST, so we fetch all alerts and
  //    check sessions in a second query per alert (same pattern as the API route).

  const { data: alerts, error: alertsErr } = await supabase
    .from("user_dropin_alerts")
    .select("id, user_id, location_id, course_title, alert_start_time, alert_end_time");

  if (alertsErr || !alerts?.length) {
    console.log("No alerts found or error:", alertsErr?.message);
    return;
  }

  // Group alerts by user_id so we send one notification per user
  const userSessions: Record<string, { course_title: string; location_id: number; sessions: { start_time: string; end_time: string }[] }[]> = {};

  await Promise.all(
    alerts.map(async (alert) => {
      let query = supabase
        .from("dropins")
        .select("start_time, end_time")
        .eq("location_id", alert.location_id)
        .ilike("course_title", `%${alert.course_title}%`)
        .eq("first_date", todayStr);

      // Apply saved time window if present
      if (alert.alert_start_time && alert.alert_end_time) {
        query = query
          .gte("start_time", alert.alert_start_time)
          .lte("start_time", alert.alert_end_time);
      }

      const { data: sessions } = await query;
      if (!sessions?.length) return;

      if (!userSessions[alert.user_id]) userSessions[alert.user_id] = [];
      userSessions[alert.user_id].push({
        course_title: alert.course_title,
        location_id:  alert.location_id,
        sessions,
      });
    })
  );

  const usersToNotify = Object.keys(userSessions);
  if (!usersToNotify.length) {
    console.log("No sessions today for any alerted user.");
    return;
  }

  console.log(`Sending notifications to ${usersToNotify.length} user(s)`);

  // ── 2. For each user, fetch their push subscriptions and send ────────────────
  await Promise.all(
    usersToNotify.map(async (userId) => {
      const { data: subs } = await supabase
        .from("user_push_subscriptions")
        .select("id, endpoint, p256dh, auth")
        .eq("user_id", userId);

      if (!subs?.length) return;

      const alerts = userSessions[userId];
      const totalSessions = alerts.reduce((n, a) => n + a.sessions.length, 0);
      const title = "FindRec TO — Today's Drop-ins";
      const body  = alerts.length === 1
        ? `${alerts[0].course_title} — ${totalSessions} session${totalSessions !== 1 ? "s" : ""} today`
        : `${alerts.length} activities with sessions today`;

      const payload = JSON.stringify({
        title,
        body,
        icon:  "/logo.png",
        badge: "/logo.png",
        data:  { url: "/dashboard" },
      });

      await Promise.all(
        subs.map(async (sub) => {
          try {
            await sendWebPush(
              { endpoint: sub.endpoint, p256dh: sub.p256dh, auth: sub.auth },
              payload,
              vapidPublicKey,
              vapidPrivateKey,
              vapidSubject,
            );
          } catch (err) {
            const status = (err as { status?: number }).status;
            if (status === 410 || status === 404) {
              // Subscription is expired/gone — remove it
              console.log(`Removing expired subscription ${sub.id}`);
              await supabase.from("user_push_subscriptions").delete().eq("id", sub.id);
            } else {
              console.error(`Push failed for sub ${sub.id}:`, err);
            }
          }
        })
      );
    })
  );

  console.log("Done.");
}

// ── Web Push send via VAPID ───────────────────────────────────────────────────
// Implements the Web Push Protocol (RFC 8030) with VAPID auth (RFC 8292).
// Uses the Web Crypto API available natively in the Deno runtime.

async function sendWebPush(
  subscription: { endpoint: string; p256dh: string; auth: string },
  payload: string,
  vapidPublicKey: string,
  vapidPrivateKey: string,
  vapidSubject: string,
): Promise<void> {
  // Import VAPID keys as CryptoKey objects
  const privateKey = await importVapidPrivateKey(vapidPrivateKey);
  const publicKeyBytes = base64urlDecode(vapidPublicKey);

  // Build VAPID JWT
  const audience = new URL(subscription.endpoint).origin;
  const expiry   = Math.floor(Date.now() / 1000) + 12 * 3600; // 12hr
  const jwt      = await buildVapidJWT({ sub: vapidSubject, aud: audience, exp: expiry }, privateKey, publicKeyBytes);

  // Encrypt the payload with ECDH + AES-GCM (RFC 8291)
  const encrypted = await encryptPayload(payload, subscription.p256dh, subscription.auth);

  const res = await fetch(subscription.endpoint, {
    method: "POST",
    headers: {
      "Content-Type":   "application/octet-stream",
      "Content-Length": String(encrypted.byteLength),
      "Content-Encoding": "aes128gcm",
      "TTL":            "86400",
      "Authorization":  `vapid t=${jwt},k=${vapidPublicKey}`,
    },
    body: encrypted,
  });

  if (!res.ok && res.status !== 201) {
    const err: { status?: number; message?: string } = new Error(`Push delivery failed: ${res.status} ${await res.text()}`);
    err.status = res.status;
    throw err;
  }
}

// ── VAPID JWT builder ─────────────────────────────────────────────────────────

async function buildVapidJWT(
  claims: { sub: string; aud: string; exp: number },
  privateKey: CryptoKey,
  publicKeyBytes: Uint8Array,
): Promise<string> {
  const header  = b64u(JSON.stringify({ typ: "JWT", alg: "ES256" }));
  const body    = b64u(JSON.stringify(claims));
  const signing = `${header}.${body}`;

  const sig = await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    privateKey,
    new TextEncoder().encode(signing),
  );

  // ECDSA DER → raw r||s conversion (needed for JWT)
  const rawSig = derToRaw(new Uint8Array(sig));
  return `${signing}.${base64urlEncode(rawSig)}`;
}

function b64u(str: string): string {
  return base64urlEncode(new TextEncoder().encode(str));
}

// ── AES-128-GCM payload encryption (RFC 8291) ─────────────────────────────────

async function encryptPayload(
  plaintext: string,
  p256dh: string,
  authSecret: string,
): Promise<ArrayBuffer> {
  const serverKeyPair = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" },
    true,
    ["deriveBits"],
  );

  const clientPublicKeyBytes = base64urlDecode(p256dh);
  const clientPublicKey = await crypto.subtle.importKey(
    "raw", clientPublicKeyBytes, { name: "ECDH", namedCurve: "P-256" }, false, [],
  );

  const sharedSecret = await crypto.subtle.deriveBits(
    { name: "ECDH", public: clientPublicKey },
    serverKeyPair.privateKey,
    256,
  );

  const serverPublicKeyRaw = await crypto.subtle.exportKey("raw", serverKeyPair.publicKey);

  const authSecretBytes = base64urlDecode(authSecret);
  const salt = crypto.getRandomValues(new Uint8Array(16));

  // HKDF: pseudorandom key
  const prk = await hkdf(
    authSecretBytes,
    concat(sharedSecret, serverPublicKeyRaw, clientPublicKeyBytes),
    labeledInfo("Content-Encoding: auth\0", 32),
    32,
  );

  // Content encryption key
  const cek = await hkdf(salt, prk, labeledInfo("Content-Encoding: aes128gcm\0", 16), 16);
  // Nonce
  const nonce = await hkdf(salt, prk, labeledInfo("Content-Encoding: nonce\0", 12), 12);

  const aesKey = await crypto.subtle.importKey("raw", cek, "AES-GCM", false, ["encrypt"]);

  // Pad plaintext: 2-byte length + content + delimiter 0x02 + padding
  const plaintextBytes = new TextEncoder().encode(plaintext);
  const padded = new Uint8Array(plaintextBytes.length + 2 + 1);
  new DataView(padded.buffer).setUint16(0, 0, false); // no padding
  padded[2] = 0x02; // record delimiter
  padded.set(plaintextBytes, 3);

  const encrypted = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv: nonce }, aesKey, padded,
  );

  // Build RFC 8291 header: salt (16) + rs (4) + idlen (1) + keyid
  const serverKeyBytes = new Uint8Array(serverPublicKeyRaw);
  const header = new Uint8Array(21 + serverKeyBytes.length);
  header.set(salt, 0);
  new DataView(header.buffer).setUint32(16, 4096, false); // record size
  header[20] = serverKeyBytes.length;
  header.set(serverKeyBytes, 21);

  return concat(header, encrypted).buffer;
}

function labeledInfo(label: string, len: number): Uint8Array {
  const enc = new TextEncoder();
  const info = new Uint8Array(enc.encode(label).length + 2);
  info.set(enc.encode(label), 0);
  new DataView(info.buffer).setUint16(enc.encode(label).length, len, false);
  return info;
}

async function hkdf(
  salt: ArrayBuffer | Uint8Array,
  ikm: ArrayBuffer | Uint8Array,
  info: Uint8Array,
  length: number,
): Promise<Uint8Array> {
  const saltKey = await crypto.subtle.importKey("raw", salt, { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const prk     = await crypto.subtle.sign("HMAC", saltKey, ikm);
  const prkKey  = await crypto.subtle.importKey("raw", prk, { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const t       = await crypto.subtle.sign("HMAC", prkKey, concat(info, new Uint8Array([1])));
  return new Uint8Array(t).slice(0, length);
}

function concat(...arrays: (ArrayBuffer | Uint8Array)[]): Uint8Array {
  const total = arrays.reduce((n, a) => n + (a instanceof ArrayBuffer ? a.byteLength : a.length), 0);
  const out   = new Uint8Array(total);
  let offset  = 0;
  for (const arr of arrays) {
    const u8 = arr instanceof Uint8Array ? arr : new Uint8Array(arr);
    out.set(u8, offset);
    offset += u8.length;
  }
  return out;
}

// ── Crypto helpers ────────────────────────────────────────────────────────────

function base64urlDecode(str: string): Uint8Array {
  const padding = "=".repeat((4 - (str.length % 4)) % 4);
  const base64  = (str + padding).replace(/-/g, "+").replace(/_/g, "/");
  return Uint8Array.from(atob(base64), (c) => c.charCodeAt(0));
}

function base64urlEncode(buf: Uint8Array): string {
  return btoa(String.fromCharCode(...buf))
    .replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
}

async function importVapidPrivateKey(base64url: string): Promise<CryptoKey> {
  const raw = base64urlDecode(base64url);
  // Wrap raw P-256 private key in a minimal SEC1 / PKCS8 envelope
  const pkcs8 = buildPkcs8(raw);
  return crypto.subtle.importKey("pkcs8", pkcs8, { name: "ECDSA", namedCurve: "P-256" }, false, ["sign"]);
}

function buildPkcs8(rawPrivKey: Uint8Array): Uint8Array {
  // Minimal PKCS#8 wrapper for P-256 private key (RFC 5958)
  // OID for id-ecPublicKey: 1.2.840.10045.2.1
  // OID for P-256: 1.2.840.10045.3.1.7
  const ecPrivKey = concat(
    new Uint8Array([0x02, 0x01, 0x01]), // version = 1
    new Uint8Array([0x04, rawPrivKey.length]), rawPrivKey,
    new Uint8Array([0xa0, 0x0a, 0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07]),
  );
  const ecPrivKeySeq = concat(new Uint8Array([0x30, ecPrivKey.length]), ecPrivKey);

  const alg = new Uint8Array([
    0x30, 0x13,
    0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01, // id-ecPublicKey
    0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, // P-256
  ]);

  const inner = concat(
    new Uint8Array([0x02, 0x01, 0x00]), // version = 0
    alg,
    new Uint8Array([0x04, ecPrivKeySeq.length]), ecPrivKeySeq,
  );

  return concat(new Uint8Array([0x30, inner.length]), inner);
}

function derToRaw(der: Uint8Array): Uint8Array {
  // Convert DER-encoded ECDSA signature to raw r||s (64 bytes for P-256)
  let offset = 2; // skip SEQUENCE tag + length
  // r integer
  offset++; // skip INTEGER tag
  const rLen = der[offset++];
  const r    = der.slice(offset, offset + rLen);
  offset += rLen;
  // s integer
  offset++; // skip INTEGER tag
  const sLen = der[offset++];
  const s    = der.slice(offset, offset + sLen);

  const raw = new Uint8Array(64);
  raw.set(r.slice(-32), 32 - Math.min(r.length, 32));
  raw.set(s.slice(-32), 64 - Math.min(s.length, 32));
  return raw;
}
